### ISSUE TITLE
[Feature Request] Fruit drops

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#111]
In 1.7.10 documentation for apple trees it states, 

> "...there is a chance that the apple will be harvested (destroyed) at the final stage. So be sure to clean the ground of fallen apples!"

This is currently not happening in 1.12

Aside from reimplementing this feature, could this also be extended to all the grapes?

**Comment by Alatyami** [comment]
This was purposefully removed. There were complaints about the Apple Trees spawning too many entities. At this time there are no plans to re-implement this.

**Comment by Deshiba** [comment]
Well, that's probably because all the leaves can drop fruits. If the rates of which are altered then there wouldn't be as many entities.

Looking at Pam's harvest craft and Dynamic trees apple trees for reference, they don't have nearly as many apples on a tree that grow slower then Growthcraft apple trees.

**Comment by Syndaryl** [comment]
I've found the sheer quantity of apples to be startling, yes. With the small amount of juice produced in the press per apple, the quantity is well matched... but for the apple-based recipes in e.g. Vanilla and Harvestcraft, the volume feels excessive. I'd like to ramp the growth rate back drastically in order to encourage having an orchard instead of just a few trees. it also looks a little odd to have this regular grid of apples under each tree.

If each leaf block "slept" a random amount of time before processing growth tics, perhaps based on some gaussian noise? it would look more natural and slow down production. Make the scale of the sleep configurable?
