### ISSUE TITLE
Ticking crash from rice crop

### ISSUE THREAD

**Issue by viceroy369** [GrowthcraftCE/Growthcraft-1.12#166]
https://paste.dimdev.org/awepibugek.mccrash

**Comment by Alatyami** [comment]
Can you paste your config file? config/growthcraft/growthcraft_rice.cfg

According to the stack trace, RiceCrop is trying to get its drops list and for some reason the growthcraft is checking if valoegheses_be:brushland_grass has the is_radioactive property and that should only be applied to growthcraft blocks. 

A screen shot of the affected area would help as well.

**Comment by viceroy369** [comment]
I hadn't touched the Growthcraft configs so it's just the default settings. Unfortunately I deleted the test world this occurred in but it was in a village.

**Comment by EightBlade** [comment]
Oh neat. Yeah I haven't touched the configs either and am running the same issue.

**Comment by IceDragon200** [comment]
@Alatyami, @EightBlade, @viceroy369  
https://github.com/GrowthcraftCE/Growthcraft-1.12/blob/cdc8504145e734886eb0b262b7292d860c4cd107/src/main/java/growthcraft/rice/common/block/BlockRiceCrop.java#L111-L122

There should be a check here to ensure you're looking at a PaddyBlock, it's likely caused by a worldgen.

The paddy was generated along with the rice, then something quietly replaced the paddy without triggering the neighbour changed callbacks which would cause the rice to drop as an item.

**Comment by Alatyami** [comment]
@IceDragon200 , that makes sense ... thanks.

**Comment by EightBlade** [comment]
Is there a way to fix it?

**Comment by Alatyami** [comment]
absolutely, it'll be in our next release

**Comment by viceroy369** [comment]
Great! ty.
