### ISSUE TITLE
 The game is crashed every time I eat or drink somethings from GC

### ISSUE THREAD

**Issue by GGPB** [GrowthcraftCE/Growthcraft-1.12#226]
when I eat any items from Growthcraft, the game crash immediately.
![unknown](https://user-images.githubusercontent.com/53569760/62297580-7a418680-b4ac-11e9-9b4b-32788a8da87d.png)

this is the mods I use right now, and this is crash report.

[crash-2019-08-01_22.02.12-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/3456954/crash-2019-08-01_22.02.12-server.txt)

I've tried growthcraft-1.12.2-4.0.5.200.DEV.a2c0ebb, the latest version, but still same.

I also using Pam's HarvestCraft and Applecore. it is fully work with no crash 
but when I eat or drink anything from Growthcraft, restore some hunger and then crash...
I've tried steamed rice, onigiri, wine, apple cider and lager.

**Comment by Alatyami** [comment]
Thank you for submitting the report, we'll try and duplicate.

**Comment by Tschipp** [comment]
Yep, also happening for me, also using AppleCore and Pam's Harvestcraft.
I'm one of the devs of Animania, and we had the same issue with our mod once. https://github.com/capnkirok/animaniamod/issues/11
AppleCore doesn't like if you decrease the ItemStack size before you apply the effects - because the item is ItemStack.EMTPY at that point.

So solution would be to call 
https://github.com/GrowthcraftCE/Growthcraft-1.12/blob/b0da6ade18bca125d1611dc7511ce0e4467dcca2/src/main/java/growthcraft/core/shared/item/GrowthcraftItemFoodBase.java#L96

before calling 
https://github.com/GrowthcraftCE/Growthcraft-1.12/blob/b0da6ade18bca125d1611dc7511ce0e4467dcca2/src/main/java/growthcraft/core/shared/item/GrowthcraftItemFoodBase.java#L91

**Comment by bloche14** [comment]
Not sure if this is the same problem but I crash whenever I try to eat a honey jar. Log:
https://paste.dimdev.org/ogekucejop.mccrash

**Comment by Alatyami** [comment]
I've moved this to be fixed prior to the 4.1 regular release

**Comment by Alatyami** [comment]
Fixed .... will go through testing and then to the next release.
