### ISSUE TITLE
Kumis and Mead un-create-able 

### ISSUE THREAD

**Issue by killerjdog51** [GrowthcraftCE/Growthcraft-1.12#272]
I'm not sure if this is an issue in version 4.1.0 (1.12.2) or if Mead and Kumis just aren't create-able yet, or perhaps I'm just trying to create them wrong. But I tried creating Kumis by putting milk inside a fermentation barrel with nether wart, and I tried creating Mead by crafting a bucket of water with a jar of honey and also tried an empty bucket with a water bucket and a jar of honey. I also tried putting honey inside of a fermentation barrel with brewers yeast to make mead must, but that didn't work either. Inside the Fermentation Barrel both Honey and Milk have the tag "Cannot Ferment". If I'm going about creating Mead and Kumis wrong I would be happy to be corrected; otherwise, I think this is an issue.

**Comment by nephatrine** [comment]
Are your milk and honey registered as "fluid_milk" and "fluid_honey" or are they fluids added by another mod with a different registry name? You probably have another mod that is adding a fluid for them (probably liquid:milk and liquid:honey instead of liquid:fluid_milk and liquid:fluid_honey). You can always change the input fluids in "fermenting.json" to accept those other milk and honeys which is what I've done in my own game. With just Growthcraft, I'm not having any issues - only when using other mods milk/honey (for instance Rustic or Inspirations).

Probably the default jsons should just come with duplicate entries with those other input fluid names since both milk and honey are added by multiple other mods.

**Comment by killerjdog51** [comment]
The only mod installed though was Growthcraft. I fixed it by deleting the instance of my modded Minecraft and reinstalling Growthcraft. Not sure why it turned out different the second time, but it works. The only thing I can think of is that perhaps I had an old config file somewhere because I used the Twitch launcher the first time and regular Minecraft the second time. Either way, I believe the issue had something to do on my end and that the mod itself is working perfectly.
