### ISSUE TITLE
[Bug] Barrel filling by right-clicking

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#79]
When in the barrel interface, right-clicking items into it results in ghost items in the player inventory and no items display in the barrel. It does function as intended though.
![rightclick](https://user-images.githubusercontent.com/10565800/50546762-8242fa80-0c2d-11e9-814c-955295b1a438.gif)

**Comment by Deshiba** [comment]
This only happens when its in the hot bar, not in the inventory slots.

**Comment by Avatair** [comment]
Confirmed. It happens only, if playing on a dedicated server. On the client-side the items are placed into the main inventory and on the server-side they are placed into the ingredient slot. Same behavior is observed for brew kettle. Other cellar devices haven't been tested, but are expected to behave the same way.

**Comment by Avatair** [comment]
Due to the inconsistent state on client and server, the item stack looks like it has been duplicated after clicking on an ingredient slot. In the main inventory the items are not really existing. Clicking on it will make it disappear.

![grafik](https://user-images.githubusercontent.com/21110130/51602616-beedd300-1f07-11e9-8355-2aefcc4442c7.png)

**Comment by Alatyami** [comment]
This bug is obsolete .... I can no longer duplicate it using 4.0.5.200
